var stringtypeExample = "This is a string";
console.log(stringtypeExample);
var numbertypeExample = 100;
console.log(numbertypeExample);
var datatyoeExample1 = true;
console.log(datatyoeExample1);
var datatyoeExample2 = false;
console.log(datatyoeExample2);
var massege = "1234";
console.log(massege);
var massegeNew = "5678";
console.log(massegeNew);
var favriotcolour = "yellow";
console.log(favriotcolour);
favriotcolour = "black";
console.log(favriotcolour);
var massegeNew1 = "123";
console.log(massegeNew1);
var userName = "Muhammad jawwad siddiqui";
console.log(userName);
var Age = 20;
console.log(Age);
var muhammadjawwadsiddiqui = true;
console.log(muhammadjawwadsiddiqui);
